## Numpy for python

Numerical Python (NumPy) is an open source Python library for scientific computing. NumPy provides a host of  features that allow a Python programmer to work with high-performance (and multidimensional) arrays and matrices. NumPy arrays are stored more efficiently than Python lists and allow mathematical operations to be vectorised, which results in significantly higher performance than with looping constructs in Python. 

Read more here: https://tinyurl.com/yxz8qfjq

Let's start by importing the modules we will be using in this notebook.

In [28]:
# Import numpy and random modules.
import random
import numpy as np

## Creating numpy arrays
There are several ways we can create numpy arrays, some examples are provided below.

In [29]:
a1 = np.array([1, 2, 3, 4, 5])             # create an array from a list.
a2 = np.array(range(20))                   # create an array from a range.
a3 = np.arange(0, 100, 5)                  # a step can be provided.
a4 = np.zeros(10, dtype=int)               # create an array containing 10 zeros of type integer.
a5 = np.linspace(1, 100, 6)                # create an array with equally spaced values.
a6 = [random.random() for _ in range(100)] # create an array containing random elements.

Print out the arrays below and check that each contains what you would expect. Change the values above and re-run the cells to see what impact this has.

In [30]:
print(f'The contents of a1 is {a1}')
print(f'The contents of a2 is {a2}')
print(f'The contents of a3 is {a3}')
print(f'The contents of a4 is {a4}')
print(f'The contents of a5 is {a5}')
print(f'The contents of a6 is {a6[:3]}') # this prints the first 3 values only.

The contents of a1 is [1 2 3 4 5]
The contents of a2 is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The contents of a3 is [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
The contents of a4 is [0 0 0 0 0 0 0 0 0 0]
The contents of a5 is [  1.   20.8  40.6  60.4  80.2 100. ]
The contents of a6 is [0.7144520070505388, 0.7310691050336303, 0.030818233219136904]


## Reshaping arrays

It is often easier to create a single dimension numpy array and then reshape it to whatever you need. See below:

In [43]:
a7 = np.arange(20)
a8 = a7.reshape(10,2)
a9 = a7.reshape(4,5)
print(f'Structure of a7\n{a7}')
print(f'Structure of a8 (10 rows, 2 columns)\n{a8}')
print(f'Structure of a9(4 rows, 5 columns)\n{a9}')

Structure of a7
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Structure of a8 (10 rows, 2 columns)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Structure of a9(4 rows, 5 columns)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
